### PR TITLE
Lower CakePHP version requirement to 3.5.

### PR DESCRIPTION
**Pull request by ADmad**
The current code will work just fine with Cake 3.5 too, so I have lowered the version constraint accordingly in composer.json. Added new travis job to prove it :slightly_smiling_face:.

### CODE REVIEW

**Comment by ADmad** [comment]
The build failures are not caused by my change. They are failing on current `master` itself as seen here https://travis-ci.org/ADmad/wrench/builds/387101798.

**Comment by ADmad** [comment]
It's this change which is causing the failures https://github.com/cakephp/bake/pull/438.

**Comment by ADmad** [comment]
Fixed with an ugly hack to check which inflection to use.

**Comment by HavokInspiration** [comment]
Ugly hack in bake task is something I can live with.

Thanks for the update 👍

**Pull request merged**
